=== geobreze/epam-web-parsing/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:rates="http://epam.com/rates"
           targetNamespace="http://epam.com/rates">
    <!-- base elements define -->
    <xs:element name="operator-name">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="MTS"/>
                <xs:enumeration value="VELCOM"/>
                <xs:enumeration value="LIFE"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="payroll">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minInclusive value="0.0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="preferential">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="DISABLED"/>
                <xs:enumeration value="ORPHAN"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <!-- complex types define -->
    <xs:complexType name="tariff-type">
        <xs:sequence>
            <xs:element ref="rates:operator-name"/>
            <xs:element ref="rates:payroll"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="preferential-tariff-type">
        <xs:complexContent>
            <xs:extension base="rates:tariff-type">
                <xs:sequence>
                    <xs:element ref="rates:preferential"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- complex elements define -->
    <xs:element name="tariff" type="rates:tariff-type"/>
    <xs:element name="preferential-tariff" type="rates:preferential-tariff-type"/>

    <!-- base element define -->
    <xs:element name="tariffs">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="rates:tariff" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element ref="rates:preferential-tariff" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== geobreze/epam-web-parsing/target/test-classes/wrongTags.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rates:tariffs
        xmlns:rates="http://epam.com/rates"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
    <rates:tariff name="Easy to say">
        <rates:operator-name>MTS</rates:operator-name>
        <rates:payroll>1004.6</rates:payroll>
    </rates:tariff>
    <rates:tariff name="Kind">
        <rates:operator-name>VELCOM</rates:operator-name>
        <rates:payroll>553.1</rates:payroll>
    </rates:tariff>
    <rates:preferential-tariff name="Unlim">
        <rates:operator-name>LIFE</rates:operator-name>
        <rates:payroll>100.5</rates:payroll>
        <rates:preferential>DISABLED</rates:preferential>
    </rates:preferential-tariff>
    <rates:preferential-tariff name="Cheaper unlim">
        <rates:incorrect>VELCOM</rates:incorrect>
        <rates:payroll>64.42</rates:payroll>
        <rates:preferential>ORPHAN</rates:preferential>
    </rates:preferential-tariff>
</rates:tariffs>

=== geobreze/epam-web-parsing/src/test/resources/preferentialTariffs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<rates:tariffs
        xmlns:rates="http://epam.com/rates"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
    <rates:preferential-tariff name="Jukebox">
        <rates:operator-name>VELCOM</rates:operator-name>
        <rates:payroll>0</rates:payroll>
        <rates:preferential>DISABLED</rates:preferential>
    </rates:preferential-tariff>
    <rates:preferential-tariff name="Orphan happiness">
        <rates:operator-name>MTS</rates:operator-name>
        <rates:payroll>10.0</rates:payroll>
        <rates:preferential>ORPHAN</rates:preferential>
    </rates:preferential-tariff>
</rates:tariffs>
